import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

import ThemeClientProvider from "./components/ThemeProvider";
import Footer from "./components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <ThemeClientProvider>
          <Header />
          {children}
          <Footer/>
        </ThemeClientProvider>
      </body>
    </html>
  );
}